In [ ]:
#Problem-1
import numpy as np
#1
empty_array = np.empty((2,2))
print(empty_array)
print()

#2
ones_array = np.ones((4,2))
print(ones_array)
print()

#3
array_fill = np.full((3,4),7)
print(array_fill)
print()

#4
original_array = np.array([[1,2,3],[4,5,6]])
print(original_array)
array_zeros_like =  np.zeros_like(original_array, dtype=float)
print(array_zeros_like)
print()

#5
given_array = np.array([[1,2,3],[4,5,6]])
array_ones = np.ones_like(given_array)
print(array_ones)
print()


#6
new_list = [1,2,3,4,5]
array_from_list = np.array(new_list)
print(array_from_list)


[[4.67423719e-310 0.00000000e+000]
 [8.02524278e-095 3.23155026e+209]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1]
 [1 1 1]]

[1 2 3 4 5]


In [ ]:
#Problem-2
import numpy as np

#1
array_arrange = np.arange(10,50)
print(array_arrange)
print()

#2
matrix_reshape = np.arange(9).reshape(3,3)
print(matrix_reshape)
print()

#3
identity_matrix_int = np.eye(3, dtype=int)
print(identity_matrix_int)
print()

#4
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array: ",random_array)
print("Mean value: ",mean_value)
print()

#5
random_array_ten = np.random.random((10,10))
min_value = random_array_ten.min()
max_value = random_array_ten.max()
print("Random array: ",random_array_ten)
print("Minimum value: ",min_value)
print("Maximum value: ",max_value)
print()

#6
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)
print()

#7
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("Original array: ", arr)
print("Reversed array: ", reversed_arr)
print()

#8
arr1 = np.zeros((5,5), dtype=int)
arr1[0,:]=1
arr1[-1,:]=1
arr1[:,0]=1
arr1[:,-1]=1
print(arr1)
print()

#9
checkerboard = np.zeros((8,8), dtype = int)
checkerboard[::2, ::2] = 1 # Set 1 for every alternate row and column starting from (0,0)
checkerboard[1::2, 1::2] = 1  # Set 1 for every alternate row and column starting from (1,1)
print(checkerboard)
print()

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

Random array:  [0.42164257 0.96937339 0.43628548 0.69468193 0.66873998 0.94722591
 0.07440746 0.8321814  0.15413159 0.15763462 0.41333358 0.03068936
 0.83670378 0.34593989 0.92124807 0.40222204 0.86761738 0.93565995
 0.91733732 0.76263562 0.45925282 0.87532595 0.36968204 0.39635317
 0.5298541  0.06865673 0.75508634 0.74222415 0.73439075 0.51426574]
Mean value:  0.5744927704479854

Random array:  [[0.37092672 0.37133757 0.85718318 0.64070773 0.96751885 0.18860676
  0.64929858 0.88570697 0.8227819  0.84594777]
 [0.82818078 0.31914476 0.7247814  0.2508718  0.85721061 0.76208254
  0.82612078 0.09624024 0.14167842 0.65626864]
 [0.75273415 0.79859459 0.42594026 0.00630813 0.31118197 0.92647094
  0.84678063 0.96653639 0.64379261 0.21357342]
 [0.62574013 0.85931811 0.91970475 0.19776786 0.6148542  0.26944079
  0.12

In [ ]:
#Problem-3
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1
add_result = x+y
print("Addition of x and y:\n",add_result)

#2
subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

#3
multiply_result = x * 2
print("\nMultiplying x by 2:\n", multiply_result)

#4
square_result = np.square(x)
print("\nSquare of each element of x:\n", square_result)

#5
dot_v_w = np.dot(v, w)
print("\nDot product of v and w:", dot_v_w)
dot_x_v = np.dot(x, v)
print("\nDot product of x and v:", dot_x_v)
dot_x_y = np.dot(x, y)
print("\nDot product of x and y:\n", dot_x_y)

#6
concat_x_y = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along row:\n", concat_x_y)
concat_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenate v and w along column:\n", concat_v_w)



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element of x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v: [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [ ]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concat_x_v = np.concatenate((x,v), axis=0)
print(concat_x_v)
#Here x is 2 dimensional array and v is 1 dimensional array. np.concatenate requires all input arrays to have the same number of dimensions.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#Problem-4
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1
#1
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)
print()

i = np.dot(A_inverse,A)
print("I = \n", i)
print("Hence A*Aᵀ = I, proved")
print()

#2
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB = \n",AB)
print()
print("BA = \n",BA)

#3
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B),np.transpose(A))
print("(AB)ᵀ = \n", AB_T)
print()
print("Bᵀ * Aᵀ = \n", B_T_A_T)
print()

#2 (Cramer's rule)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

#calculate determinant of A
det_A = np.linalg.det(A)
print(f"det(A) = {det_A}")
print()

#Create matrices A_x, A_y, and A_z by replacing columns of A with B
A_x = A.copy() #Creates a copy of matrix A called A_x.
A_x[:, 0] = B[:, 0] #This line replaces the first column of A_x with the first column of B.

A_y = A.copy()
A_y[:, 1] = B[:, 0]

A_z = A.copy()
A_z[:, 2] = B[:, 0]

#Calculate the determinants of A_x, A_y, and A_z
det_A_x = np.linalg.det(A_x)
det_A_y = np.linalg.det(A_y)
det_A_z = np.linalg.det(A_z)

#Calculate the solutions for x, y, z using Cramer's Rule
x = det_A_x / det_A
y = det_A_y / det_A
z = det_A_z / det_A

print(f"Solution:\nx = {x}\ny = {y}\nz = {z}")
print()

#3
# Compute the inverse of A_eq
A_inv = np.linalg.inv(A_eq)

# Solve for X using the inverse method
X = np.dot(A_inv, B_eq)
print("Solution for [x, y, z]:\n", X)

Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

I = 
 [[1.00000000e+00 0.00000000e+00]
 [5.55111512e-16 1.00000000e+00]]
Hence A*Aᵀ = I, proved

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]
(AB)ᵀ = 
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ = 
 [[23 51]
 [13 29]]

det(A) = -19.000000000000004

Solution:
x = 2.0000000000000004
y = 1.0
z = -1.9999999999999993

Solution for [x, y, z]:
 [[ 2.]
 [ 1.]
 [-2.]]
